### PR TITLE
use admin_centre node for relation centroid where available

### PR DESCRIPTION
**Pull request by missinglink**
as per discussion in https://github.com/pelias/pbf2json/issues/96 some relations have a node member of role 'admin_centre' which we should favour over the computed geographic centroid.

### CODE REVIEW

**Comment by timonmasberg** [comment]
Wouldn't it be better if we check that the relation is of type `"boundary":"administrative"` (that's where `admin_centre` is of relevance) before we go through every member for every relation?

**Comment by missinglink** [comment]
> Wouldn't it be better if we check that the relation is of type `"boundary":"administrative"` (that's where `admin_centre` is of relevance) before we go through every member for every relation?

It's really not very expensive since the members are already in memory and there's only one per *immediate* member (so one per ring), it probably only takes a fraction of a millisecond to compute.

That being said, if it's only relevant for `boundary=administrative` then we can only apply it on those, are we 100% sure that's correct? I had a look at the wiki and it seems logical.

**Comment by missinglink** [comment]
Added a `boundary=administrative` check via rebase.

**Comment by missinglink** [comment]
```bash
go run ./... -tags 'official_status:de~Land' /data/osm/hamburg-latest.osm.pbf | jq .centroid

2021/07/21 12:27:39 [warn] lookup failed for way: 279806560 noderefs not found: W279806560
{
  "lat": "53.5437641",
  "lon": "10.0099133",
  "type": "admin_centre"
}
```

**Pull request merged**
